[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"

[tool.autoflake]
in-place = true
expand-star-imports = true
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-duplicate-keys = true
remove-unused-variables = true
quiet = true

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = [
    "google.*",
    "hyperscript.*",
    "ruamel.*",
    "setuptools.*",
    "sqlmesh.*",
    "sqlmesh_tests.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-n 0 --dist=worksteal"
